name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm ci --verbose
      - name: List node_modules
        run: ls node_modules
      - name: Check if vitest is installed
        run: pnpm list vitest
      - name: Run lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test
      - name: Build project
        run: pnpm build
      