name: CI
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Configure PNPM
        run: pnpm config set auto-install-peers true  # Adjust this based on your project's requirements
      - name: Install dependencies
        run: pnpm ci  # This replaces 'pnpm install --frozen-lockfile'
